Modo de Trabajo: Publicar Suscribir
TP-IASC/CarpinchoMQ pull request #35
Opened 2021-12-01 23:59 UTC by dpeccia

## Que significa que una cola tenga este modo de trabajo?

Que si un Productor le pushea un mensaje a la cola, este mensaje será (asincronicamente) enviado a todos los suscriptores que tenga la cola (en ese momento nos guardamos todos los consumidores que nos tienen que mandar ACKs para ese mensaje particular en una lista `:consumers_that_did_not_ack`). 

En cuanto los suscriptores vayan contestandole con acks a la cola, los borramos de esa lista para ese mensaje, y nos fijamos si la lista queda vacia: 
- si no queda vacia no hacemos nada
- si quedo vacia borramos el mensaje de la cola (porque quiere decir que todos los consumidores a los que les habiamos enviado el mensaje nos respondieron con un ACK)

En cuanto a la replica, cada vez que modificamos algo del estado le enviamos ese cambio a la replica para que tambien se mantenga actualizada

Ejemplo:
* Levanto 2 nodos
* En el nodo 1 creo una cola con el modo publicar-suscribir
* En el nodo 2 creo 2 consumidores y los suscribo a la cola 1
* Ahora pusheo un mensaje (y puedo poner un sleep de unos 20 segundos en Consumer en el handle cast que recibe el mensaje, para que tarde un poco en contestar con el ack y pueda chequear algunas cosas)
* Mientras esperamos los acks, vemos el estado de la cola, aca podremos ver los suscriptores de la cola, el mensaje almacenado en la cola, y que para ese mensaje tenemos 2 consumidores que todavia no respondieron con ack
![image](https://user-images.githubusercontent.com/42644816/144332974-75bd2674-c2e2-40a8-8443-02ea8501fe3e.png)
* En cuanto lleguen los 2 acks, se va a eliminar el mensaje de la cola, por lo que si volvemos a consultar el estado de la cola este no tendrá elementos. (si un consumidor no respondiera con ack, el mensaje nunca se borraria de la cola, quizas en un futuro podemos hacer un proceso batch que si pasó mucho tiempo y no se recibieron los acks para ese mensaje, lo borre)
![image](https://user-images.githubusercontent.com/42644816/144333084-4e4f34fe-a91f-488f-9b40-53d26185bb37.png)

2021-12-02 12:20 UTC, facuhump2409 requested changes

2021-12-02 12:20 UTC, facuhump2409 commented on lib/client/consumer.ex
> +  end
Diego aca quizas podemos mejorar el nombre de este metodo porque no termino de entender bien que hace

2021-12-02 12:20 UTC, facuhump2409 commented on lib/model/primary_queue.ex
> +    send_to_replica(state.name, { :add_receivers_to_state_message, subscribers, message })
Esto me hace un poco de ruido diego, esta bien que tengamos el envio a las replicas antes que al master? Se que es medio border, pero me hace ruido que las replicas quizas tengan antes la info que el master

2021-12-03 01:55 UTC, dpeccia commented on lib/client/consumer.ex
> +  end
Tenemos uno igual en la queue:
![image](https://user-images.githubusercontent.com/42644816/144531270-9f9fe309-5ec5-45eb-9187-0c4dc8add607.png)

Es un chiche nomas, la verdad es que no es muy importante, es para que cuando queres tirarle un mensaje async al consumidor en vez de hacer `GenServer.cast....` hagas `Consumer.cast.....`. Agrega como un poquito mas de expresividad nomas. Si se te ocurre algun nombre piola avisame y lo cambio, pero me parecio que quedaba mas o menos claro

2021-12-03 01:58 UTC, dpeccia commented on lib/model/primary_queue.ex
> +    send_to_replica(state.name, { :add_receivers_to_state_message, subscribers, message })
Tengo entendido (quizas me equivoco), que el estado en un handle_cast recien se actualiza cuando llegas a la linea del `:noreply` que tiene que ser lo ultimo que haga el metodo. La verdad no estoy muy seguro de como se podria hacer que el envio a la replica se mande despues de eso

2021-12-03 02:31 UTC, facuhump2409 commented on lib/client/consumer.ex
> +  end
Mmm oka dejemoslo asi

2021-12-03 02:31 UTC, facuhump2409 approved these changes

2021-12-03 03:45 UTC, CimimUxMaio approved these changes
Te creo ciegamente que funciona todo :P

Los comentarios que deje son mas que nada para mencionar y tener en cuenta para despues o para proximos PRs

2021-12-03 03:45 UTC, CimimUxMaio commented on lib/model/replica_queue.ex
> +    { :noreply, Map.put(state, :elements, [%{message: message, consumers_that_did_not_ack: []}|state.elements]) }
Medio una boludez, pero para que no queden tan largas y complejas, este tipo de lineas, podes usar una linea mas arriba para crear el element:

```
element = %{message: message, consumers_that_did_not_ack: []}
{ :noreply, Map.put(state, :elements, [element | state.elements]) }
```

2021-12-03 03:45 UTC, CimimUxMaio commented on lib/client/producer.ex
> +      OK.failure({:non_existent_work_mode, "Work mode \"#{work_mode}\" does not exist. Available work modes: :publish_subscribe and :work_queue"})
El modelado de los modos de trabajo me hubiera gustado modelarlos como "modulos polimorficos" (si es que esto tiene sentido).

La idea seria que en el init de la cola le pasas por parametro en vez de `:publish_subscribe` un modulo. Algo como:
```
Queue.new :cola1, 10, WorkQueue
```
o
```
Queue.new :cola1, 10, PubSub
```

Esto te evitaria estos ifs, y podrias usarlos de forma polimorfica como por ejemplo:
```
new_state = state.work_mode.distribute_message(msg, state)

bla...
```

Con esto te ahorras varios ifs y seria mas "extensible". De todas formas, como andamos cortos de tiempo esto puede quedar para otro momento. Si asi funciona dejemoslo asi.

2021-12-03 03:47 UTC, dpeccia commented on lib/model/replica_queue.ex
> +    { :noreply, Map.put(state, :elements, [%{message: message, consumers_that_did_not_ack: []}|state.elements]) }
_Sono d'accordo_ sep, tenes razon, no me di cuenta jajaja

2021-12-03 03:47 UTC, dpeccia commented on lib/client/producer.ex
> +      OK.failure({:non_existent_work_mode, "Work mode \"#{work_mode}\" does not exist. Available work modes: :publish_subscribe and :work_queue"})
Si vas al issue lo dejé como un niceToHave en un bullet para que si nos queda tiempo lo hagamos, peeeero andamos cortinas de tiempo

2021-12-03 04:03 UTC, ramacal approved these changes

2021-12-03 15:31 UTC, CimimUxMaio commented on lib/client/producer.ex
> +      OK.failure({:non_existent_work_mode, "Work mode \"#{work_mode}\" does not exist. Available work modes: :publish_subscribe and :work_queue"})
Que se mergee pues 👌

2021-12-03 19:47 UTC, merged