DELETE /queues/:name endpoint
TP-IASC/CarpinchoMQ pull request #48
Opened 2021-12-08 18:31 UTC by CimimUxMaio

Agregue este endpoint para poder borrar colas desde el front

2021-12-08 19:48 UTC, facuhump2409 requested changes

2021-12-08 19:48 UTC, facuhump2409 commented on lib/comunication/http/http_server.ex
> +    handle_post_response(conn, Producer.delete_queue(queue_name))
Por que aca dice "handle_post_response"? No seria "handle_delete_response"?

2021-12-08 21:47 UTC, CimimUxMaio commented on lib/comunication/http/http_server.ex
> +    handle_post_response(conn, Producer.delete_queue(queue_name))
True, pero es porque el  nombre de la funcion es una verga jaja.
Ahora veo que le pongo.

2021-12-08 21:51 UTC, CimimUxMaio commented on lib/comunication/http/http_server.ex
> +    handle_post_response(conn, Producer.delete_queue(queue_name))
Ahi le cambie el nombre

2021-12-09 01:11 UTC, dpeccia approved these changes

2021-12-09 01:34 UTC, facuhump2409 approved these changes

2021-12-09 01:52 UTC, merged